# run in debug mode to emit more debugging information
debug: false

# SPARQL endpoint and examples (required)
sparql:
  # TODO: config via env $SPARQL
  endpoint: http://fuseki:3030/n4o
  examples:
    # examples given in files
    - queries/*.rq
    # example given in config file
    - name: List all classes
      query: |
        SELECT DISTINCT ?class WHERE { [] a ?class }  examples:

stage: ./stage 

# Links to tools and references (optional)
tools:
  - name: LIDO-Schulung
    url: https://docs.nfdi4culture.de/lido-schulung
    description: Einf√ºhrung in das LIDO-Format
  - name: LIDO2RDF
    description: Convert LIDO XML to RDF
    path: /lido2rdf/
    proxy: http://lido2rdf:5000/
